# Change these first
owner: Julius-Ulee # Your GitHub organization or username, where this repository lives
repo: Status-Page-Advanced # The name of this repository

sites:
  - name: School Programs
    url: https://julius-ulee.github.io/School-Programs/
    icon: https://julius-ulee.github.io/School-Programs/assets/images/stationery.png
  - name: AmeliaBot Discord
    url: https://ameliabot-discord.uzumekiulee.repl.co
    icon: https://static.vecteezy.com/system/resources/previews/018/930/718/original/discord-logo-discord-icon-transparent-free-png.png
  - name: Crypto Mining
    url: https://julius-ulee.github.io/Crypto-Mining/
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Bitcoin.svg/1200px-Bitcoin.svg.png
  - name: Portfolio
    url: https://julius-ulee.github.io/
    icon: https://assets.holopin.io/eyJidWNrZXQiOiJob2xvcGluLWFzc2V0cyIsImtleSI6ImFzc2V0cy9jbGt4aGVvazEyMTczMGZtcHA5N2xnN3p2IiwiZWRpdHMiOnsicm90YXRlIjpudWxsfX0=
  - name: Holobytes Hunter
    url: https://julius-ulee.github.io/holobyte.github.io/
    icon: https://www.holopin.io/images/logo.png

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.ameliabot.dev
  baseUrl: /Status-Page-Advanced
  faviconSvg: https://julius-ulee.github.io/School-Programs/assets/images/favicon.ico
  logoUrl: https://julius-ulee.github.io/School-Programs/assets/images/favicon.ico
  theme: light
  name: School Programs Status
  introTitle: "School Programs Status is committed to creating an efficient bandwidth marketplace on Web3."
  introMessage: The monitoring **real-time** data from our [GitHub repository](https://github.com/Julius-Ulee/Status).
  navbar:
    - title: Home
      href: /Status-Page-Advanced
    - title: School Programs
      href: https://julius-ulee.github.io/School-Programs/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Discord
      href: https://discord.gg/VzUR95y

i18n:
  footer: This page is hosted on GitHub [Julius Ulee]($REPO) project since @2023-09-10, & created by [Julius Ulee](https://julius-ulee.github.io/Status-Page-Advanced/).
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
